AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  paycheck-calculator-api

  Sample SAM Template for paycheck-calculator-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PaycheckCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: paycheck_calculator/
      Handler: app.app
      Runtime: python3.7

      Events:
        Test:
          Type: Api
          Properties:
            Path: /
            Method: get
        GetCalculation:
          Type: Api
          Properties:
            Path: /calculate_paycheck
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PaycheckCalculatorApi:
    Description: "API Gateway endpoint URL for Prod stage for Paycheck calculator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  PaycheckCalculatorFunction:
    Description: "Paycheck Calculator Lambda Function ARN"
    Value: !GetAtt PaycheckCalculatorFunction.Arn
  PaycheckCalculatorFunctionIamRole:
    Description: "Implicit IAM Role created for Paycheck Calculator function"
    Value: !GetAtt PaycheckCalculatorFunctionRole.Arn
